#!/usr/bin/ruby

require "json.rb"

f = ARGV[0]
unless f && File.file?(f)
    puts "usage: runwithhalive script.hs"
    exit 1
end

conf = {"cfgFileTypes"=>["hs", "pd", "frag", "vert"], "cfgMainFilePath"=> f, "cfgExtensions"=>[], "cfgIncludeDirs"=>[], "cfgDisableExtensions"=>[]}
conf_json = JSON.generate conf
json_path = "/tmp/runwithhalive_halive.json"
File.write json_path, conf_json
cmd = "halive -cfg #{json_path}"
system cmd
